#!/bin/sh
# Stock xl2tpd/swanctl init scripts must not compete for the same daemon ports.
/etc/init.d/xl2tpd disable
/etc/init.d/xl2tpd stop
/etc/init.d/swanctl disable
/etc/init.d/swanctl stop
uci -q batch <<'EOF'
set firewall.cudy_l2tp_ike=rule
set firewall.cudy_l2tp_ike.name='Cudy L2TP IKE'
set firewall.cudy_l2tp_ike.src='wan'
set firewall.cudy_l2tp_ike.proto='udp'
set firewall.cudy_l2tp_ike.dest_port='500 4500'
set firewall.cudy_l2tp_ike.family='ipv4'
set firewall.cudy_l2tp_ike.target='ACCEPT'
set firewall.cudy_l2tp_ike.enabled='0'
set firewall.cudy_l2tp_esp=rule
set firewall.cudy_l2tp_esp.name='Cudy L2TP ESP'
set firewall.cudy_l2tp_esp.src='wan'
set firewall.cudy_l2tp_esp.proto='esp'
set firewall.cudy_l2tp_esp.family='ipv4'
set firewall.cudy_l2tp_esp.target='ACCEPT'
set firewall.cudy_l2tp_esp.enabled='0'
set firewall.cudy_l2tp_zone=zone
set firewall.cudy_l2tp_zone.name='cudy_vpn'
add_list firewall.cudy_l2tp_zone.device='l2tpvpn'
set firewall.cudy_l2tp_zone.input='ACCEPT'
set firewall.cudy_l2tp_zone.output='ACCEPT'
set firewall.cudy_l2tp_zone.forward='REJECT'
set firewall.cudy_l2tp_zone.family='ipv4'
set firewall.cudy_l2tp_zone.mtu_fix='1'
set firewall.cudy_l2tp_zone.enabled='0'
set firewall.cudy_l2tp_lan=forwarding
set firewall.cudy_l2tp_lan.src='cudy_vpn'
set firewall.cudy_l2tp_lan.dest='lan'
set firewall.cudy_l2tp_lan.enabled='0'
set firewall.cudy_l2tp_wan=forwarding
set firewall.cudy_l2tp_wan.src='cudy_vpn'
set firewall.cudy_l2tp_wan.dest='wan'
set firewall.cudy_l2tp_wan.enabled='0'
commit firewall
EOF
chmod 600 /etc/config/cudy_l2tp
/etc/init.d/cudy_l2tp enable
exit 0

