include $(TOPDIR)/rules.mk
LUCI_TITLE:=Cudy L2TP/IPsec VPN server
LUCI_DEPENDS:=+lua +libuci-lua +xl2tpd +ppp +strongswan-charon +strongswan-swanctl +strongswan-mod-openssl +strongswan-mod-kernel-netlink +strongswan-mod-socket-default +strongswan-mod-random +kmod-nft-xfrm
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
include $(TOPDIR)/feeds/luci/luci.mk

