include $(TOPDIR)/rules.mk
LUCI_TITLE:=Cudy dual-band Wi-Fi and client steering
LUCI_DEPENDS:=+lua +libuci-lua +luci-lib-nixio +luci-lib-jsonc +flock +usteer +wpad-mbedtls
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
